### ISSUE TITLE
Release should not depends on snapshot version

### ISSUE THREAD

**Issue by Fuud** [OpenHFT/JLBH#1]
`net.openhft:jlbh:jar:1.0.0` should not depends on `net.openhft:chronicle-bom:pom:2.17-SNAPSHOT`

**Comment by RobAustin** [comment]
We will release it, you should use the last release version from maven central. This is not a bug.

**Comment by dpisklov** [comment]
Will need to re-release it, thanks for pointing out

**Comment by dpisklov** [comment]
Done
