### ISSUE TITLE
Print progress during benchmark

### ISSUE THREAD

**Issue by QIvan** [OpenHFT/JLBH#11]
If you don't mind, I'd like to make a small feature request: could JLBH prints progress during a benchmark as well as it does during a warmup? 
Every time I start using jlbh, I interrupt first runs, because I thought I did something wrong and my benchmark hangs, but then, with several `println`, I realize, no, it just requires that much of time. 

thanks!

**Comment by peter-lawrey** [comment]
A progress message now appears every 5 seconds.
