### ISSUE TITLE
Real benchmarks examples

### ISSUE THREAD

**Issue by QIvan** [OpenHFT/JLBH#3]
Hi! Thank you for the tool, it looks very nice but I wonder where are the real-world examples? 
I mean in your [series of articles](http://www.rationaljava.com/2016/04/a-series-of-posts-on-jlbh-java-latency.html) you mentioned that 
> The code for JLBH can be found in Chronicle-Core library which can be found on GitHub over [here](https://github.com/OpenHFT/Chronicle-Core/tree/master/src/main/java/net/openhft/chronicle/core/jlbh).

but the link is not valid anymore. I struggled to find any benchmarks in your repos but everything that I found was without any jlbh mention, e.g. 
https://github.com/OpenHFT/Chronicle-Core/blob/master/benchmarks/src/main/java/net/openhft/chronicle/core/benchmark/Main.java
https://github.com/OpenHFT/Chronicle-Map/blob/master/src/test/java/net/openhft/chronicle/map/CHMLatencyTestMain.java

 Do you still recommend to use this tool? If so, could you kindly help me with some "real" examples? 

Thank you in advance!

**Comment by dpisklov** [comment]
@QIvan we use JLBH across many of our projects, some of which are closed-source and indeed we recommend using it for latency benchmarks but it doesn't mean it's intended to replace JMH in microbenchmarking space.
Examples of latency benchmarks in open source:
https://github.com/OpenHFT/Chronicle-Queue/tree/master/src/test/java/net/openhft/chronicle/queue/bench
Another real world example is here:
http://www.rationaljava.com/2016/04/jlbh-examples-4-benchmarking-quickfix.html

but it's not open-source (Chronicle FIX is paid closed-source product).

In general, please do not use github for questions (use stackoverflow instead), github is for real issues
