### ISSUE TITLE
Fixed test JLBHTest.shouldWriteResultToTheOutputProvided

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/JLBH#31]
I appears to only fail on java 11

see https://teamcity.chronicle.software/viewLog.html?buildId=642242&tab=buildResultsDiv&buildTypeId=OpenHFT_BuildAll_BuildJava11compileJava11

![image](https://user-images.githubusercontent.com/6506056/148437968-02018194-37f9-4c34-af32-9379c4118962.png)

org.junit.ComparisonFailure: expected:<[]Warm up complete ......> but was:<[
]Warm up complete ......>
org.junit.ComparisonFailure: 
expected:<[]Warm up complete ......> but was:<[
]Warm up complete ......>
	at net.openhft.chronicle.jlbh.JLBHTest.shouldWriteResultToTheOutputProvided(JLBHTest.java:86)
------- Stdout: -------
predictableTaskExpectedResult = Warm up complete ...
-------------------------------- BENCHMARK RESULTS (RUN 1) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 8.07 / 11.66  12.46 / 12.56  12.56 - 12.56
A (9,001)                                       50/90 99/99.9 99.99 - worst was 7.06 / 10.67  11.47 / 11.57  11.57 - 11.57
B (9,001)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- BENCHMARK RESULTS (RUN 2) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 8.07 / 11.66  12.46 / 12.56  12.56 - 12.56
A (9,000)                                       50/90 99/99.9 99.99 - worst was 7.06 / 10.67  11.47 / 11.57  11.57 - 11.57
B (9,000)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- BENCHMARK RESULTS (RUN 3) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 6.10 / 9.71  10.51 / 10.61  10.61 - 10.61
A (9,000)                                       50/90 99/99.9 99.99 - worst was 5.11 / 8.72  9.52 / 9.58  9.62 - 9.62
B (9,000)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (end to end) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            8.07         8.07         6.10        17.69
90.0:           11.66        11.66         9.71        11.82
99.0:           12.46        12.46        10.51        11.02
worst:          12.56        12.56        10.61        10.93
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (A) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            7.06         7.06         5.11        20.29
90.0:           10.67        10.67         8.72        12.99
99.0:           11.47        11.47         9.52        12.03
worst:          11.57        11.57         9.62        11.92
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (B) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            0.10         0.10         0.10         0.00
90.0:            0.10         0.10         0.10         0.00
99.0:            0.10         0.10         0.10         0.00
worst:           0.10         0.10         0.10         0.00
-------------------------------------------------------------------------------------------------------------------

expected = Warm up complete ...
-------------------------------- BENCHMARK RESULTS (RUN 1) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 8.07 / 11.66  12.46 / 12.56  12.56 - 12.56
A (9,001)                                       50/90 99/99.9 99.99 - worst was 7.06 / 10.67  11.47 / 11.57  11.57 - 11.57
B (9,001)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- BENCHMARK RESULTS (RUN 2) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 8.07 / 11.66  12.46 / 12.56  12.56 - 12.56
A (9,000)                                       50/90 99/99.9 99.99 - worst was 7.06 / 10.67  11.47 / 11.57  11.57 - 11.57
B (9,000)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- BENCHMARK RESULTS (RUN 3) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 6.10 / 9.71  10.51 / 10.61  10.61 - 10.61
A (9,000)                                       50/90 99/99.9 99.99 - worst was 5.11 / 8.72  9.52 / 9.58  9.62 - 9.62
B (9,000)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (end to end) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            8.07         8.07         6.10        17.69
90.0:           11.66        11.66         9.71        11.82
99.0:           12.46        12.46        10.51        11.02
worst:          12.56        12.56        10.61        10.93
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (A) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            7.06         7.06         5.11        20.29
90.0:           10.67        10.67         8.72        12.99
99.0:           11.47        11.47         9.52        12.03
worst:          11.57        11.57         9.62        11.92
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (B) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            0.10         0.10         0.10         0.00
90.0:            0.10         0.10         0.10         0.00
99.0:            0.10         0.10         0.10         0.00
worst:           0.10         0.10         0.10         0.00
-------------------------------------------------------------------------------------------------------------------

actual = 
Warm up complete ...
-------------------------------- BENCHMARK RESULTS (RUN 1) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 8.07 / 11.66  12.46 / 12.56  12.56 - 12.56
A (9,001)                                       50/90 99/99.9 99.99 - worst was 7.06 / 10.67  11.47 / 11.57  11.57 - 11.57
B (9,001)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- BENCHMARK RESULTS (RUN 2) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 8.07 / 11.66  12.46 / 12.56  12.56 - 12.56
A (9,000)                                       50/90 99/99.9 99.99 - worst was 7.06 / 10.67  11.47 / 11.57  11.57 - 11.57
B (9,000)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- BENCHMARK RESULTS (RUN 3) --------------------------------------------------------
Run time: ...s, distribution: NORMAL
Correcting for co-ordinated:true
Target throughput:1000000/s = 1 message every 1us
End to End: (9,000)                             50/90 99/99.9 99.99 - worst was 6.10 / 9.71  10.51 / 10.61  10.61 - 10.61
A (9,000)                                       50/90 99/99.9 99.99 - worst was 5.11 / 8.72  9.52 / 9.58  9.62 - 9.62
B (9,000)                                       50/90 99/99.9 99.99 - worst was 0.100 / 0.100  0.100 / 0.100  0.100 - 0.100
OS Jitter ...
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (end to end) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            8.07         8.07         6.10        17.69
90.0:           11.66        11.66         9.71        11.82
99.0:           12.46        12.46        10.51        11.02
worst:          12.56        12.56        10.61        10.93
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (A) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            7.06         7.06         5.11        20.29
90.0:           10.67        10.67         8.72        12.99
99.0:           11.47        11.47         9.52        12.03
worst:          11.57        11.57         9.62        11.92
-------------------------------------------------------------------------------------------------------------------
-------------------------------- SUMMARY (B) -----------------------------------------------------------
Percentile   run1         run2         run3      % Variation
50.0:            0.10         0.10         0.10         0.00
90.0:            0.10         0.10         0.10         0.00
99.0:            0.10         0.10         0.10         0.00
worst:           0.10         0.10         0.10         0.00
-------------------------------------------------------------------------------------------------------------------
« Hide stacktrace Copy to clipboard

**Comment by hft-team-city** [comment]
Released in [JLBH-1.22ea6](https://github.com/OpenHFT/JLBH/releases/jlbh-1.22ea6), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
