### ISSUE TITLE
OSJitterSampler is never terminated

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/JLBH#43]
When jitter sampling is turned on, it's never terminated, even when the test is finished.

**Comment by hft-team-city** [comment]
Released in [JLBH-1.23ea2](https://github.com/OpenHFT/JLBH/releases/jlbh-1.23ea2), [BOM-2.24ea40](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea40)
