### ISSUE TITLE
deprecate packages so that they are no longer in chronicle.software.core move them to chronicle.software.jlbh

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/JLBH#8]

**Comment by glukos** [comment]
We use `net.openhft.chronicle` package prefix for public products.

JLBH classes moved from `net.openhft.chronicle.core.jlbh` to `net.openhft.chronicle.jlbh`. Old classes are kept intact with `@Deprecated` annotation.

All classes are either package-local or used in API - I didn't move anything to `internal` package.
